// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBir0KckXFkseGJUD08BZDUI8e2oPyicEw',
    appId: '1:791657874797:web:14fbf7b7985b018bfb8664',
    messagingSenderId: '791657874797',
    projectId: 'cafe-menu-digital',
    authDomain: 'cafe-menu-digital.firebaseapp.com',
    storageBucket: 'cafe-menu-digital.firebasestorage.app',
    measurementId: 'G-RJCB0M5T37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYT7SUCDTJA-Na4uY_bNNWbXS-LJdXd90',
    appId: '1:791657874797:android:69b3487b38dd6643fb8664',
    messagingSenderId: '791657874797',
    projectId: 'cafe-menu-digital',
    storageBucket: 'cafe-menu-digital.firebasestorage.app',
  );
}
